### ISSUE TITLE
Does not build with latest cl-sdl2

### ISSUE THREAD

**Issue by quicklisp** [Failproofshark/cl-sdl2-ttf#13]
I get this:

    ; caught ERROR:
    ;   during macroexpansion of (AUTOCOLLECT (PTR) (CHECK-NULL #) ...). Use *BREAK-ON-SIGNALS* to intercept.
    ;    Trying to use AUTOCOLLECT without TRIVIAL-GARBAGE

**Comment by Failproofshark** [comment]
I believe this has been fixed thanks to @mfiano . Thanks again @mfiano
