### ISSUE TITLE
RenderText_Shaded is missing the second color

### ISSUE THREAD

**Issue by stacksmith** [Failproofshark/cl-sdl2-ttf#2]
The Shaded functions seem to be specified same as Blended and Solid, with a single color argument.  According to documentation, Shaded functions have an additional color for the background, like this:

SDL_Surface *TTF_RenderText_Shaded(TTF_Font *font, const char *text, SDL_Color fg, SDL_Color bg)

**Comment by Failproofshark** [comment]
Sorry for the late response, and thanks for the heads up. I will update the definition as soon as I can (most likely some time this week)
