### ISSUE TITLE
was-init returns integer

### ISSUE THREAD

**Issue by ReinUsesLisp** [Failproofshark/cl-sdl2-ttf#8]
sdl2-ttf:was-init returns 0 when it's not initialized and 1 when initialized. It'd be easy to change so it returns t and nil, but it may break API contract with existing applications.

```lisp
CL-USER> (sdl2-ttf:was-init)
0
CL-USER> (sdl2-ttf:init)
0
CL-USER> (sdl2-ttf:was-init)
1
```

**Comment by Failproofshark** [comment]
Thanks @ReinUsesLisp . I'm a little afraid of returning anything other than the original value returned by the library itself for the reason you just mentioned; changing the value to return t or nil could break whatever is depending on the normal 0 or 1. Instead, I think it would probably be better for whatever is using this library to abstract that detail.
